/* This file contains stub implementations of the AUTOSAR RTE functions.
   The stub implementations can be used for testing the generated code in
   Simulink, for example, in SIL/PIL simulations of the component under
   test. Note that this file should be replaced with an appropriate RTE
   file when deploying the generated code outside of Simulink.

   This file is generated for:
   Atomic software component:  "BSD_ECU"
   ARXML schema: "4.4"
   File generated on: "Sun Jun 07 00:50:09 2026"  */

#ifndef Rte_BSD_ECU_h
#define Rte_BSD_ECU_h
#include "Rte_Type.h"
#include "Compiler.h"

/* Data access functions */
#define Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Distance_Left Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_RadarData_Distance_Left

float32 Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Distance_Left(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Distance_Right Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_RadarData_Distance_Right

float32 Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Distance_Right(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Gear_Position Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_VehicleData_Gear_Position

uint8 Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Gear_Position(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Status_Left Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_RadarData_Status_Left

uint8 Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Status_Left(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Status_Right Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_RadarData_Status_Right

uint8 Rte_IRead_BSD_Algorithm_Run_RPort_RadarData_Status_Right(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Steering_Angle Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_VehicleData_Steering_Angle

float32 Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Steering_Angle(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Turn_Signal Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_VehicleData_Turn_Signal

uint8 Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Turn_Signal(void);

#define Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Vehicle_Speed Rte_IRead_BSD_ECU_BSD_Algorithm_Run_RPort_VehicleData_Vehicle_Speed

float32 Rte_IRead_BSD_Algorithm_Run_RPort_VehicleData_Vehicle_Speed(void);

#define Rte_IWrite_BSD_Algorithm_Run_PPort_WarningOutput_Warning_Status Rte_IWrite_BSD_ECU_BSD_Algorithm_Run_PPort_WarningOutput_Warning_Status

void Rte_IWrite_BSD_Algorithm_Run_PPort_WarningOutput_Warning_Status(uint8 u);

#define Rte_IWriteRef_BSD_Algorithm_Run_PPort_WarningOutput_Warning_Status Rte_IWriteRef_BSD_ECU_BSD_Algorithm_Run_PPort_WarningOutput_Warning_Status

uint8* Rte_IWriteRef_BSD_Algorithm_Run_PPort_WarningOutput_Warning_Status(void);

#define Rte_IWrite_BSD_Algorithm_Run_PPort_WarningOutput_LED_Output Rte_IWrite_BSD_ECU_BSD_Algorithm_Run_PPort_WarningOutput_LED_Output

void Rte_IWrite_BSD_Algorithm_Run_PPort_WarningOutput_LED_Output(uint8 u);

#define Rte_IWriteRef_BSD_Algorithm_Run_PPort_WarningOutput_LED_Output Rte_IWriteRef_BSD_ECU_BSD_Algorithm_Run_PPort_WarningOutput_LED_Output

uint8* Rte_IWriteRef_BSD_Algorithm_Run_PPort_WarningOutput_LED_Output(void);

#define Rte_IWrite_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_L_Fault Rte_IWrite_BSD_ECU_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_L_Fault

void Rte_IWrite_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_L_Fault(uint8 u);

#define Rte_IWriteRef_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_L_Fault Rte_IWriteRef_BSD_ECU_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_L_Fault

uint8* Rte_IWriteRef_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_L_Fault(void);

#define Rte_IWrite_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_R_Fault Rte_IWrite_BSD_ECU_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_R_Fault

void Rte_IWrite_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_R_Fault(uint8 u);

#define Rte_IWriteRef_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_R_Fault Rte_IWriteRef_BSD_ECU_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_R_Fault

uint8* Rte_IWriteRef_BSD_Algorithm_Run_PPort_FaultStatus_Sensor_R_Fault(void);

/* Entry point functions */
extern FUNC(void, BSD_ECU_CODE) BSD_System_Init(void);
extern FUNC(void, BSD_ECU_CODE) BSD_Algorithm_Run(void);

#endif
